In [1]:
import pandas as pd

KeyboardInterrupt: 

In [ ]:
data=pd.read_csv("D:\\kt\\adult.csv")

In [5]:
data.head()

NameError: name 'data' is not defined

In [ ]:
data.shape

(48842, 15)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   age              48842 non-null  int64 
 1   workclass        48842 non-null  object
 2   fnlwgt           48842 non-null  int64 
 3   education        48842 non-null  object
 4   educational-num  48842 non-null  int64 
 5   marital-status   48842 non-null  object
 6   occupation       48842 non-null  object
 7   relationship     48842 non-null  object
 8   race             48842 non-null  object
 9   gender           48842 non-null  object
 10  capital-gain     48842 non-null  int64 
 11  capital-loss     48842 non-null  int64 
 12  hours-per-week   48842 non-null  int64 
 13  native-country   48842 non-null  object
 14  income           48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB


In [ ]:
data.isnull().sum()

age                0
workclass          0
fnlwgt             0
education          0
educational-num    0
marital-status     0
occupation         0
relationship       0
race               0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
native-country     0
income             0
dtype: int64

In [ ]:
data.dropna()

age     workclass  fnlwgt     education  educational-num  \
0       25       Private  226802          11th                7   
1       38       Private   89814       HS-grad                9   
2       28     Local-gov  336951    Assoc-acdm               12   
3       44       Private  160323  Some-college               10   
4       18             ?  103497  Some-college               10   
...    ...           ...     ...           ...              ...   
48837   27       Private  257302    Assoc-acdm               12   
48838   40       Private  154374       HS-grad                9   
48839   58       Private  151910       HS-grad                9   
48840   22       Private  201490       HS-grad                9   
48841   52  Self-emp-inc  287927       HS-grad                9   

           marital-status         occupation relationship   race  gender  \
0           Never-married  Machine-op-inspct    Own-child  Black    Male   
1      Married-civ-spouse    Farming-fishing      Husband  White    Male   
2      Married-civ-spouse    Protective-serv      Husband  White    Male   
3      Married-civ-spouse  Machine-op-inspct      Husband  Black    Male   
4           Never-married                  ?    Own-child  White  Female   
...                   ...                ...          ...    ...     ...   
48837  Married-civ-spouse       Tech-support         Wife  White  Female   
48838  Married-civ-spouse  Machine-op-inspct      Husband  White    Male   
48839             Widowed       Adm-clerical    Unmarried  White  Female   
48840       Never-married       Adm-clerical    Own-child  White    Male   
48841  Married-civ-spouse    Exec-managerial         Wife  White  Female   

       capital-gain  capital-loss  hours-per-week native-country income  
0                 0             0              40  United-States  <=50K  
1                 0             0              50  United-States  <=50K  
2                 0             0              40  United-States   >50K  
3              7688             0              40  United-States   >50K  
4                 0             0              30  United-States  <=50K  
...             ...           ...             ...            ...    ...  
48837             0             0              38  United-States  <=50K  
48838             0             0              40  United-States   >50K  
48839             0             0              40  United-States  <=50K  
48840             0             0              20  United-States  <=50K  
48841         15024             0              40  United-States   >50K  

[48842 rows x 15 columns]

In [ ]:
data['capital-gain'].mean()

1079.0676262233324

In [ ]:
data['capital-gain']=data['capital-gain'].replace(0,1079)

In [ ]:
data['capital-loss'].mean()

87.50231358257237

In [ ]:
data['capital-loss']=data['capital-loss'].replace(0,87)

In [ ]:
data['income'].unique()

array(['<=50K', '>50K'], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['income'] = le.fit_transform(data['income'])

In [ ]:
data['income'].unique()

array([0, 1])

In [ ]:
data.replace('?',np.nan,inplace=True)

<IPython.core.display.Javascript object>

In [ ]:
data=data.dropna()

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 45222 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   age              45222 non-null  int64 
 1   workclass        45222 non-null  object
 2   fnlwgt           45222 non-null  int64 
 3   education        45222 non-null  object
 4   educational-num  45222 non-null  int64 
 5   marital-status   45222 non-null  object
 6   occupation       45222 non-null  object
 7   relationship     45222 non-null  object
 8   race             45222 non-null  object
 9   gender           45222 non-null  object
 10  capital-gain     45222 non-null  int64 
 11  capital-loss     45222 non-null  int64 
 12  hours-per-week   45222 non-null  int64 
 13  native-country   45222 non-null  object
 14  income           45222 non-null  int32 
dtypes: int32(1), int64(6), object(8)
memory usage: 5.3+ MB


In [ ]:
del data['native-country']

In [ ]:
data['gender'].unique()

array(['Male', 'Female'], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['gender'] = le.fit_transform(data['gender'])

In [ ]:
data['gender'].unique()

array([1, 0])

In [ ]:
data.head()

age  workclass  fnlwgt     education  educational-num      marital-status  \
0   25    Private  226802          11th                7       Never-married   
1   38    Private   89814       HS-grad                9  Married-civ-spouse   
2   28  Local-gov  336951    Assoc-acdm               12  Married-civ-spouse   
3   44    Private  160323  Some-college               10  Married-civ-spouse   
5   34    Private  198693          10th                6       Never-married   

          occupation   relationship   race  gender  capital-gain  \
0  Machine-op-inspct      Own-child  Black       1          1079   
1    Farming-fishing        Husband  White       1          1079   
2    Protective-serv        Husband  White       1          1079   
3  Machine-op-inspct        Husband  Black       1          7688   
5      Other-service  Not-in-family  White       1          1079   

   capital-loss  hours-per-week  income  
0            87              40       0  
1            87              50       0  
2            87              40       1  
3            87              40       1  
5            87              30       0

In [ ]:
data['race'].unique()

array(['Black', 'White', 'Other', 'Amer-Indian-Eskimo',
       'Asian-Pac-Islander'], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['race'] = le.fit_transform(data['race'])

In [ ]:
data['race'].unique()

array([2, 4, 3, 0, 1])

In [ ]:
data['relationship'].unique()

array(['Own-child', 'Husband', 'Not-in-family', 'Unmarried', 'Wife',
       'Other-relative'], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['relationship'] = le.fit_transform(data['relationship'])

In [ ]:
data['marital-status'].unique()

array(['Never-married', 'Married-civ-spouse', 'Widowed', 'Separated',
       'Divorced', 'Married-spouse-absent', 'Married-AF-spouse'],
      dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['marital-status'] = le.fit_transform(data['marital-status'])

In [ ]:
data['marital-status'].unique()

array([4, 2, 6, 5, 0, 3, 1])

In [ ]:
data['workclass'].unique()

array(['Private', 'Local-gov', 'Self-emp-not-inc', 'Federal-gov',
       'State-gov', 'Self-emp-inc', 'Without-pay'], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['workclass'] = le.fit_transform(data['workclass'])

In [ ]:
data['workclass'].unique()

array([2, 1, 4, 0, 5, 3, 6])

In [ ]:
data['education'].unique()

array(['11th', 'HS-grad', 'Assoc-acdm', 'Some-college', '10th',
       'Prof-school', '7th-8th', 'Bachelors', 'Masters', '5th-6th',
       'Assoc-voc', '9th', 'Doctorate', '12th', '1st-4th', 'Preschool'],
      dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['education'] = le.fit_transform(data['education'])

In [ ]:
data['education'].unique()

array([ 1, 11,  7, 15,  0, 14,  5,  9, 12,  4,  8,  6, 10,  2,  3, 13])

In [ ]:
data.head()

age  workclass  fnlwgt  education  educational-num  marital-status  \
0   25          2  226802          1                7               4   
1   38          2   89814         11                9               2   
2   28          1  336951          7               12               2   
3   44          2  160323         15               10               2   
5   34          2  198693          0                6               4   

          occupation  relationship  race  gender  capital-gain  capital-loss  \
0  Machine-op-inspct             3     2       1          1079            87   
1    Farming-fishing             0     4       1          1079            87   
2    Protective-serv             0     4       1          1079            87   
3  Machine-op-inspct             0     2       1          7688            87   
5      Other-service             1     4       1          1079            87   

   hours-per-week  income  
0              40       0  
1              50       0  
2              40       1  
3              40       1  
5              30       0

In [ ]:
data['occupation'].unique()

array(['Machine-op-inspct', 'Farming-fishing', 'Protective-serv',
       'Other-service', 'Prof-specialty', 'Craft-repair', 'Adm-clerical',
       'Exec-managerial', 'Tech-support', 'Sales', 'Priv-house-serv',
       'Transport-moving', 'Handlers-cleaners', 'Armed-Forces'],
      dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['occupation'] = le.fit_transform(data['occupation'])

In [ ]:
data['occupation'].unique()

array([ 6,  4, 10,  7,  9,  2,  0,  3, 12, 11,  8, 13,  5,  1])

In [ ]:
data.head()

age  workclass  fnlwgt  education  educational-num  marital-status  \
0   25          2  226802          1                7               4   
1   38          2   89814         11                9               2   
2   28          1  336951          7               12               2   
3   44          2  160323         15               10               2   
5   34          2  198693          0                6               4   

   occupation  relationship  race  gender  capital-gain  capital-loss  \
0           6             3     2       1          1079            87   
1           4             0     4       1          1079            87   
2          10             0     4       1          1079            87   
3           6             0     2       1          7688            87   
5           7             1     4       1          1079            87   

   hours-per-week  income  
0              40       0  
1              50       0  
2              40       1  
3              40       1  
5              30       0

In [ ]:
#data.to_csv("D:\\kt\\cleaned_kt.csv")

In [ ]:
df=pd.read_csv("D:\\kt\\cleaned_kt.csv")

In [ ]:
df.head()

age  workclass  fnlwgt  education  educational-num  marital-status  \
0   25          2  226802          1                7               4   
1   38          2   89814         11                9               2   
2   28          1  336951          7               12               2   
3   44          2  160323         15               10               2   
4   34          2  198693          0                6               4   

   occupation  relationship  race  gender  capital-gain  capital-loss  \
0           6             3     2       1          1079            87   
1           4             0     4       1          1079            87   
2          10             0     4       1          1079            87   
3           6             0     2       1          7688            87   
4           7             1     4       1          1079            87   

   hours-per-week  income  
0              40       0  
1              50       0  
2              40       1  
3              40       1  
4              30       0

In [ ]:
correlation_matrix = df.corr()
correlation_with_income = correlation_matrix['income'].abs().sort_values(ascending=True)
print(correlation_with_income)

fnlwgt             0.007264
workclass          0.015659
occupation         0.049787
race               0.070844
education          0.081196
capital-loss       0.149112
marital-status     0.192711
capital-gain       0.214476
gender             0.215760
hours-per-week     0.227199
age                0.237040
relationship       0.253402
educational-num    0.332800
income             1.000000
Name: income, dtype: float64


In [ ]:
from sklearn.feature_selection import f_classif
import pandas as pd
X = data.drop('income', axis=1)
y = data['income']
fisher_scores, _ = f_classif(X, y)
fisher_scores_df = pd.DataFrame({'Feature': X.columns, 'Fisher_Score': fisher_scores})
fisher_scores_df = fisher_scores_df.sort_values(by='Fisher_Score', ascending=True)
print(fisher_scores_df)

            Feature  Fisher_Score
2            fnlwgt      2.386133
1         workclass     11.091075
6        occupation    112.369235
8              race    228.098747
3         education    300.107490
11     capital-loss   1028.309707
5    marital-status   1744.123164
10     capital-gain   2180.423774
9            gender   2207.890435
12   hours-per-week   2461.281534
0               age   2692.087895
7      relationship   3102.946175
4   educational-num   5632.170804


In [ ]:
df=df.drop('fnlwgt', axis=1)

In [ ]:
df=df.drop('workclass', axis=1)

In [ ]:
df.head()

age  education  educational-num  marital-status  occupation  relationship  \
0   25          1                7               4           6             3   
1   38         11                9               2           4             0   
2   28          7               12               2          10             0   
3   44         15               10               2           6             0   
4   34          0                6               4           7             1   

   race  gender  capital-gain  capital-loss  hours-per-week  income  
0     2       1          1079            87              40       0  
1     4       1          1079            87              50       0  
2     4       1          1079            87              40       1  
3     2       1          7688            87              40       1  
4     4       1          1079            87              30       0

In [ ]:
#df.to_csv("D:\\kt\\final_selection.csv")

In [ ]:
d=pd.read_csv("D:\\kt\\final_selection.csv")

In [ ]:
x=d.drop('income', axis=1)

In [ ]:
x

age  education  educational-num  marital-status  occupation  \
0       25          1                7               4           6   
1       38         11                9               2           4   
2       28          7               12               2          10   
3       44         15               10               2           6   
4       34          0                6               4           7   
...    ...        ...              ...             ...         ...   
45217   27          7               12               2          12   
45218   40         11                9               2           6   
45219   58         11                9               6           0   
45220   22         11                9               4           0   
45221   52         11                9               2           3   

       relationship  race  gender  capital-gain  capital-loss  hours-per-week  
0                 3     2       1          1079            87              40  
1                 0     4       1          1079            87              50  
2                 0     4       1          1079            87              40  
3                 0     2       1          7688            87              40  
4                 1     4       1          1079            87              30  
...             ...   ...     ...           ...           ...             ...  
45217             5     4       0          1079            87              38  
45218             0     4       1          1079            87              40  
45219             4     4       0          1079            87              40  
45220             3     4       1          1079            87              20  
45221             5     4       0         15024            87              40  

[45222 rows x 11 columns]

In [ ]:
y=d['income']

In [ ]:
y

0        0
1        0
2        1
3        1
4        0
        ..
45217    0
45218    1
45219    0
45220    0
45221    1
Name: income, Length: 45222, dtype: int64

In [ ]:
from sklearn.decomposition import PCA
n_components = 9
pca = PCA(n_components=n_components)
x = pca.fit_transform(x)
columns = [f'PC{i+1}' for i in range(n_components)]
x = pd.DataFrame(x, columns=columns)
final_data_pca = pd.concat([x, y], axis=1)
print("Explained Variance Ratio:", pca.explained_variance_ratio_)
final_data_pca.head()

Explained Variance Ratio: [9.97245465e-01 2.74794473e-03 3.29772617e-06 2.51875026e-06
 3.00804484e-07 2.85890608e-07 9.25758108e-08 4.41923439e-08
 3.55001977e-08]


PC1        PC2        PC3       PC4       PC5       PC6       PC7  \
0 -1010.868352 -86.107598 -12.658020  4.100987  2.948062  9.349975 -0.171589   
1 -1010.864953 -86.058747   3.394852  8.736985 -2.013599  0.561986  1.146841   
2 -1010.867535 -86.095591  -9.611404  3.326749  4.846581  1.046433 -2.720942   
3  5598.126287 -75.633775   3.971725 -3.158397 -1.406947 -4.082662  1.745756   
4 -1010.868481 -86.106191  -8.063988 -8.558829  4.263993  9.913445  0.238412   

        PC8       PC9  income  
0  1.477207  0.279182       0  
1 -1.369935  0.179562       0  
2 -1.824639 -0.138002       1  
3 -1.274354  0.254095       1  
4 -0.517266  1.219341       0

In [ ]:
from sklearn.feature_selection import RFE
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error as mae
from sklearn.metrics import mean_squared_error as mse
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,random_state=42)
rf = RandomForestClassifier(n_estimators=10, random_state=42)
num_features_to_select = 9
rfe = RFE(estimator=rf, n_features_to_select=num_features_to_select)
rfe.fit(x_train, y_train)
selected_features = x_train.columns[rfe.support_]
rf_selected = RandomForestClassifier(n_estimators=10, random_state=42)
rf_selected.fit(x_train[selected_features], y_train)
print("MODEL ACCURACY =", rf_selected.score(x_train[selected_features], y_train))
print("ACCURACY =", rf_selected.score(x_test[selected_features], y_test))
ypred_selected = rf_selected.predict(x_test[selected_features])
print("MAE =", mae(y_test, ypred_selected))
print("MSE =", mse(y_test, ypred_selected))
print("RMSE =", mse(y_test, ypred_selected, squared=False))

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

MODEL ACCURACY = 0.9492495231777096
ACCURACY = 0.8430071862907684
MAE = 0.15699281370923163
MSE = 0.15699281370923163
RMSE = 0.39622318673852447
